import { addDays, setHours, setMinutes, subDays } from "date-fns";
import { Events } from "@prisma/client";

export const sampleEvents: Events[] = [
  {
    id: "1",
    title: "Prenatal Checkup – Sitio 1 Mothers",
    description:
      "Monthly prenatal assessment for expectant mothers in Sitio 1.",
    start: subDays(new Date(), 10),
    end: subDays(new Date(), 10),
    allDay: true,
    color: "sky",
    location: "Birthing Home – Examination Room 1",
    createdAt: new Date("2024-10-05T09:30:00"),
    updatedAt: new Date("2024-10-12T14:20:00"),
    userId: null,
  },
  {
    id: "2",
    title: "Doctor's Consultation – Dr. Maria Santos",
    description: "OB-GYN consultation and ultrasound appointments.",
    start: setMinutes(setHours(subDays(new Date(), 3), 9), 0),
    end: setMinutes(setHours(subDays(new Date(), 3), 12), 0),
    color: "emerald",
    location: "Birthing Home – Consultation Room",
    createdAt: new Date("2024-10-08T11:15:00"),
    updatedAt: new Date("2024-10-15T16:45:00"),
    userId: null,
    allDay: false,
  },
  {
    id: "3",
    title: "Health Education: Proper Nutrition During Pregnancy",
    description:
      "Educational talk about balanced meals and vitamin intake for pregnant women.",
    start: setMinutes(setHours(new Date(), 14), 0),
    end: setMinutes(setHours(new Date(), 16), 0),
    color: "amber",
    location: "Community Hall – Lobo Birthing Home",
    createdAt: new Date("2024-10-10T08:00:00"),
    updatedAt: new Date("2024-10-18T10:30:00"),
    userId: null,
    allDay: false,
  },
  {
    id: "4",
    title: "Free Checkup Day – Open for All Pregnant Women",
    description: "Free prenatal examination and vital signs monitoring.",
    start: addDays(new Date(), 1),
    end: addDays(new Date(), 1),
    allDay: true,
    color: "rose",
    location: "Birthing Home – Main Lobby",
    createdAt: new Date("2024-10-12T13:45:00"),
    updatedAt: new Date("2024-10-20T09:15:00"),
    userId: null,
  },
  {
    id: "5",
    title: "Midwives Meeting and Case Review",
    description:
      "Weekly meeting to discuss recent patient updates and delivery outcomes.",
    start: setMinutes(setHours(addDays(new Date(), 2), 13), 0),
    end: setMinutes(setHours(addDays(new Date(), 2), 15), 0),
    color: "orange",
    location: "Staff Conference Room",
    createdAt: new Date("2024-10-03T10:20:00"),
    updatedAt: new Date("2024-10-17T15:00:00"),
    userId: null,
    allDay: false,
  },
  {
    id: "6",
    title: "Expected Delivery – Baby Dela Cruz",
    description: "Estimated due date for Mrs. Dela Cruz's delivery.",
    start: addDays(new Date(), 3),
    end: addDays(new Date(), 3),
    allDay: true,
    color: "violet",
    location: "Birthing Room 2",
    createdAt: new Date("2024-10-07T14:30:00"),
    updatedAt: new Date("2024-10-19T11:20:00"),
    userId: null,
  },
  {
    id: "7",
    title: "Postpartum Follow-Up Checkup",
    description:
      "Examination and counseling for mothers 2 weeks after delivery.",
    start: setMinutes(setHours(addDays(new Date(), 5), 10), 0),
    end: setMinutes(setHours(addDays(new Date(), 5), 12), 0),
    color: "sky",
    location: "Birthing Home – Room 3",
    createdAt: new Date("2024-10-09T16:10:00"),
    updatedAt: new Date("2024-10-21T13:40:00"),
    userId: null,
    allDay: false,
  },
  {
    id: "8",
    title: "Newborn Care and Vaccination Day",
    description: "Immunization for infants and guidance on newborn care.",
    start: addDays(new Date(), 6),
    end: addDays(new Date(), 6),
    allDay: true,
    color: "rose",
    location: "Community Health Center",
    createdAt: new Date("2024-10-11T07:50:00"),
    updatedAt: new Date("2024-10-22T08:30:00"),
    userId: null,
  },
  {
    id: "9",
    title: "Lamaze Class – Breathing and Relaxation Techniques",
    description:
      "Hands-on session for mothers and partners to prepare for childbirth.",
    start: setMinutes(setHours(addDays(new Date(), 7), 9), 0),
    end: setMinutes(setHours(addDays(new Date(), 7), 11), 30),
    color: "violet",
    location: "Birthing Home – Training Room",
    createdAt: new Date("2024-10-04T12:25:00"),
    updatedAt: new Date("2024-10-16T14:55:00"),
    userId: null,
    allDay: false,
  },
  {
    id: "10",
    title: "Barangay Health Workers Coordination Meeting",
    description:
      "Monthly coordination for maternal care outreach in nearby sitios.",
    start: setMinutes(setHours(addDays(new Date(), 10), 14), 0),
    end: setMinutes(setHours(addDays(new Date(), 10), 16), 0),
    color: "emerald",
    location: "Municipal Health Office",
    createdAt: new Date("2024-10-06T09:40:00"),
    updatedAt: new Date("2024-10-23T10:15:00"),
    userId: null,
    allDay: false,
  },
  {
    id: "11",
    title: "Maternal Care Orientation for First-Time Moms",
    description:
      "Orientation on pregnancy awareness, birth plans, and postnatal care.",
    start: addDays(new Date(), 12),
    end: addDays(new Date(), 12),
    allDay: true,
    color: "amber",
    location: "Birthing Home – Function Hall",
    createdAt: new Date("2024-10-13T15:20:00"),
    updatedAt: new Date("2024-10-24T11:45:00"),
    userId: null,
  },
  {
    id: "12",
    title: "Monthly Supply Check and Facility Sanitation",
    description:
      "Inventory check of birthing kits, vitamins, and sanitation supplies.",
    start: setMinutes(setHours(addDays(new Date(), 13), 8), 30),
    end: setMinutes(setHours(addDays(new Date(), 13), 11), 0),
    color: "orange",
    location: "Storage and Sanitation Area",
    createdAt: new Date("2024-10-02T08:15:00"),
    updatedAt: new Date("2024-10-25T09:50:00"),
    userId: null,
    allDay: false,
  },
  {
    id: "13",
    title: "Pregnancy Support Group Session",
    description:
      "Sharing experiences and emotional support for expectant mothers.",
    start: setMinutes(setHours(addDays(new Date(), 14), 15), 0),
    end: setMinutes(setHours(addDays(new Date(), 14), 17), 0),
    color: "rose",
    location: "Community Center – Sitio 2",
    createdAt: new Date("2024-10-14T10:05:00"),
    updatedAt: new Date("2024-10-26T16:30:00"),
    userId: null,
    allDay: false,
  },
];
